### ISSUE TITLE
Infrastructuur inrichten back-end

### ISSUE THREAD

**Issue by sdhoek** [sdhoek/sleepmap#15]

**Comment by sdhoek** [comment]
Bijna klaar

**Comment by ynte** [comment]
Kosten-baten? OSMR ziet er wel interessant uit. We kunnen backend profilen om evt bottenecks te identificeren.

**Comment by stvno** [comment]
Routing server met OSRM (zonder onbegluurd) staat online:
http://88.99.33.248:5000/route/v1/bike/5.085639953613281,52.08963261363972;5.1340484619140625,52.09490597957163
